// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "CPU": {
      /**
       * Usage
       * @returns {Promise<string>}  - Go Type: string
       */
      "Usage": () => {
        return window.go.main.CPU.Usage();
      },
    },
  },

};
export default go;
